-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NDiplomacy.MAX_INFAMY_GAIN = 1

NDefines.NCharacter.AGE_OF_MARRIAGE_MALE = 14
NDefines.NCharacter.AGE_OF_MARRIAGE_FEMALE = 14

NDefines.NReligion.CREATE_ANTIPOPE_PRESTIGE_COST = 5000

NDefines.NMilitary.LEVY_MAINTENANCE_FACTOR = 1.4
NDefines.NMilitary.RETINUE_INCREASE_PER_TECH = 0
NDefines.NMilitary.RETINUE_HIRE_COST_MULTIPLIER = 0.08
NDefines.NMilitary.RETINUE_REINFORCE_RATE = 0.05
NDefines.NMilitary.RETINUE_CONSTANT_COST = 1.4

NDefines.NNomad.MAX_MANPOWER_POPULATION_MULTIPLIER = 0.15
